click-sound:
  sound: BLOCK_NOTE_BLOCK_PLING
  volume: 0.4
  pitch: 1.0

gui_open_sound:
  sound: "BLOCK_BARREL_OPEN"
  volume: 0.6
  pitch: 1.6

purchase-sound:
  sound: "ENTITY_PLAYER_LEVELUP"
  volume: 0.5
  pitch: 1.2

# MySQL configuration section
storage:
  type: 'MYSQL' # Change to 'MySQL' to use MySQL
mysql:
  host: 'localhost'
  port: 3306
  database: 'cookieclicker'
  username: 'root'
  password: '131219'

# Todo: Remove synchronized
# Todo: Fix buying a upgrade buys it multiple times
# Todo: Remove clicker



