name: CookieClicker
version: '${project.version}'
main: de.stylelabor.dev.cookieclicker.CookieClicker
api-version: '1.20'
commands:
  cookieclicker:
    description: cookieclicker command
    usage: /cookieclicker